apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookinfo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  gcePersistentDisk:
    pdName: bookinfo
    fsType: pd-balanced
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookinfo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
