apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: bookinfo
spec: 
  capacity: 
    storage: 200Mi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cache 
  gcePersistentDisk: 
    pdName: bookinfo
    fsType: pd-balanced
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: bookinfo-pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  storageClassName: cache 
  resources: 
    requests: 
      storage: 200Mi
