apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token
  annotations:
    tekton.dev/git-0: github.com
    tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: ___GITLAB_USER___
  password: ___GITLAB_TOKEN___
